spring:
  profiles:
    active: dev
  application:
    name: framework

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.springboot.framework
  configuration:
    cache-enabled: false
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true
